Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -25,6 +25,11 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
 
+      name: Run a failing script
+        run: |
+          echo "This is an intentional error"
+          exit 1
+
       # Runs a single command using the runners shell
       - name: Run a one-line script
         run: echo Hello, world!
